query PageContent($uri: String = "") {
	nodeByUri(uri: $uri) {
		__typename
		... on Page {
			id
			databaseId
			title
			date
			backgroundColour {
				backgroundColour
				hideNavigation
			}
			editorBlocks {
				...CommonBlockFields
			}
		}
		... on Nhtbl_project {
			id
			databaseId
			title
			excerpt
			nhtblClients {
				nodes {
					name
					id
					parentId
					slug
				}
			}
			nhtblServices {
				nodes {
					id
					name
					slug
					parentId
				}
			}
			projectData {
				startDate
				endDate
				imageGallery {
					nodes {
						altText
						colorPalette
						dominantColor
						secondaryColor
						mediaDetails {
							...MediaDetailsFragment
						}
					}
				}
			}
			editorBlocks {
				...CommonBlockFields
			}
		}
	}
}

fragment BlockBasicFields on EditorBlock {
	name
	parentClientId
	clientId
	type
}

fragment CommonBlockFields on EditorBlock {
	...BlockBasicFields
	... on CoreVideo {
		attributes {
			autoplay
			preload
			src
			metadata
			muted
			controls
			caption
			poster
			align
			loop
			className
		}
	}
	... on CorePostTitle {
		renderedHtml
		attributes {
			className
			fontFamily
			fontSize
			textColor
			textAlign
			level
			align
		}
	}
	... on CoreEmbed {
		renderedHtml
		attributes {
			align
			url
		}
	}
	... on CoreImage {
		altText
		colorPalette
		dominantColor
		secondaryColor
		mediaDetails {
			sizes(exclude: [MEDIUM_LARGE, MEDIUM]) {
				sourceUrl
				height
				width
				mimeType
				name
			}
		}
		attributes {
			title
			alt
			url
			caption
			aspectRatio
			scale
			width
			height
			href
			linkTarget
			className
			align
		}
	}
	... on CoreParagraph {
		attributes {
			content
			fontFamily
			fontSize
			textColor
			align
			className
			cssClassName
		}
	}
	... on CoreFootnotes {
		renderedHtml
		innerBlocks {
			name
		}
		attributes {
			metadata
		}
	}
	... on CoreMore {
		attributes {
			customText
		}
	}
	... on CoreList {
		attributes {
			ordered
			reversed
			start
			textColor
			type
		}
	}
	... on CoreListItem {
		attributes {
			content
			fontSize
			fontFamily
			textColor
		}
	}
	... on CoreAccordionPanel {
		attributes {
			openByDefault
		}
	}
	... on CoreAccordionHeading {
		attributes {
			fontSize
			fontFamily
			showIcon
			style
			title
		}
	}
	... on CoreHeading {
		attributes {
			content
			className
			cssClassName
			fontFamily
			fontSize
			textColor
			textAlign
			level
			align
		}
	}
	... on CoreColumns {
		attributes {
			backgroundColor
			textColor
			layout
			className
			verticalAlignment
			style
			align
			isStackedOnMobile
		}
	}
	... on CoreColumn {
		attributes {
			backgroundColor
			textColor
			layout
			className
			verticalAlignment
			width
			style
		}
	}
	... on CoreGroup {
		attributes {
			backgroundColor
			textColor
			align
			style
			layout
			behavior
			minHeight
			contentAlign
			reveal
			revealDirection
			revealStagger
			parallax
		}
	}
	... on CoreButton {
		attributes {
			backgroundColor
			textColor
			borderColor
			className
			style
			fontSize
			fontFamily
			linkTarget
			text
			url
		}
	}
	... on CoreButtons {
		attributes {
			align
			layout
		}
	}
	... on CoreSpacer {
		attributes {
			height
			style
		}
	}
	... on CoreQuote {
		attributes {
			citation
			layout
			textAlign
			className
			fontFamily
			fontSize
			textColor
			align
			value
		}
	}
	... on CoreLatestPosts {
		attributes {
			postsToShow
			displayPostDate
			className
			align
		}
		resolvedPosts {
			...ResolvedPostFields
		}
	}
	... on CoreQuery {
		attributes {
			align
			className
		}
		resolvedPosts {
			...ResolvedPostFields
		}
	}
	... on AcfHomePageHero {
		attributes {
			backgroundColor
			align
		}
		homePageHero {
			images(first: 100) {
				nodes {
					altText
					colorPalette
					dominantColor
					secondaryColor
					mediaType
					mimeType
					mediaItemUrl
					mediaDetails {
						...MediaDetailsFragment
					}
				}
			}
		}
	}
	... on AcfServicePush {
		attributes {
			align
			backgroundColor
		}
		servicePush {
			service {
				nodes {
					slug
					... on Page {
						id
						title
						uri
						featuredImage {
							node {
								altText
								colorPalette
								dominantColor
								secondaryColor
								mediaDetails {
									...MediaDetailsFragment
								}
							}
						}
					}
				}
			}
		}
	}
	... on AcfGalerie {
		attributes {
			align
		}
		galerie {
			galerie {
				nodes {
					mediaType
					mimeType
					mediaItemUrl
					caption(format: RENDERED)
					altText
					colorPalette
					dominantColor
					secondaryColor
					mediaDetails {
						...MediaDetailsFragment
					}
				}
			}
		}
	}
	... on AcfPortfolioBlock {
		attributes {
			align
			backgroundColor
			textColor
			style
		}
		portfolioBlock {
			displayMode
			enableSearch
			showTags
			projectSource
			projectsPerPage
			sortOrder
			selectedService {
				nodes {
					slug
					name
				}
			}
			specificProjects {
				nodes {
					slug
					... on Nhtbl_project {
						id
						uri
						title(format: RENDERED)
						excerpt(format: RENDERED)
						nhtblClients {
							nodes {
								name
								slug
							}
						}
						nhtblServices {
							nodes {
								name
								slug
								parentId
								id
							}
						}
						projectData {
							startDate
							endDate
						}
						featuredImage {
							node {
								altText
								colorPalette
								dominantColor
								secondaryColor
								mediaDetails {
									...MediaDetailsFragment
								}
							}
						}
					}
				}
			}
		}
	}
	... on AcfLinkBlock {
		attributes {
			align
			backgroundColor
		}
		linkBlock {
			internalLink {
				nodes {
					slug
					uri
				}
			}
			externalLink {
				url
				title
				target
			}
		}
	}
	... on AcfSurveyBlock {
		surveyBlock {
			questions {
				required
				allowOther
				useDefaultLikertOptions
				options {
					optionLabel
					optionValue
				}
				questionKey
				questionText
				questionType
			}
		}
	}
	... on AcfImageGallery {
		attributes {
			align
			backgroundColor
			style
			className
		}
		imageGallery {
			intervalMs
			aspectRatio
			caption
			fullWidth
			fullHeight
			images {
				nodes {
					altText
					sourceUrl
					mediaType
					mediaDetails {
						...MediaDetailsFragment
					}
				}
			}
		}
	}
	... on AcfSlideshow {
		attributes {
			align
			backgroundColor
			style
			className
		}
		slideshow {
			autoplay
			intervalMs
			aspectRatio
			showNavigation
		}
	}
	... on AcfSlide {
		slide {
			caption
			image {
				node {
					altText
					colorPalette
					dominantColor
					secondaryColor
					mediaType
					mimeType
					mediaDetails {
						...MediaDetailsFragment
					}
				}
			}
		}
	}
	... on AcfSubpageNavigation {
		attributes {
			align
		}
		navItems {
			databaseId
			title
			uri
			isCurrent
		}
	}
}

fragment MediaDetailsFragment on MediaDetails {
	width
	height
	sizes {
		name
		sourceUrl
		width
		height
	}
}

fragment ResolvedPostFields on ResolvedPost {
	title
	date
	uri
	excerpt
	featuredImage {
		sourceUrl
		altText
		sizes {
			sourceUrl
			width
			height
			name
			mimeType
		}
	}
}
