/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface KgBackground {
    }
    interface KgCard {
        "artworktitle": string;
        "description": string;
        "directions": string;
        "images": Array<any>;
        "maplink": string;
        "name": string;
    }
    interface KgFooter {
    }
    interface KgIntro {
        "introtext": string;
    }
    interface KgLogo {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLKgBackgroundElement extends Components.KgBackground, HTMLStencilElement {
    }
    var HTMLKgBackgroundElement: {
        prototype: HTMLKgBackgroundElement;
        new (): HTMLKgBackgroundElement;
    };
    interface HTMLKgCardElement extends Components.KgCard, HTMLStencilElement {
    }
    var HTMLKgCardElement: {
        prototype: HTMLKgCardElement;
        new (): HTMLKgCardElement;
    };
    interface HTMLKgFooterElement extends Components.KgFooter, HTMLStencilElement {
    }
    var HTMLKgFooterElement: {
        prototype: HTMLKgFooterElement;
        new (): HTMLKgFooterElement;
    };
    interface HTMLKgIntroElement extends Components.KgIntro, HTMLStencilElement {
    }
    var HTMLKgIntroElement: {
        prototype: HTMLKgIntroElement;
        new (): HTMLKgIntroElement;
    };
    interface HTMLKgLogoElement extends Components.KgLogo, HTMLStencilElement {
    }
    var HTMLKgLogoElement: {
        prototype: HTMLKgLogoElement;
        new (): HTMLKgLogoElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-root": HTMLAppRootElement;
        "kg-background": HTMLKgBackgroundElement;
        "kg-card": HTMLKgCardElement;
        "kg-footer": HTMLKgFooterElement;
        "kg-intro": HTMLKgIntroElement;
        "kg-logo": HTMLKgLogoElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppRoot {
    }
    interface KgBackground {
    }
    interface KgCard {
        "artworktitle"?: string;
        "description"?: string;
        "directions"?: string;
        "images"?: Array<any>;
        "maplink"?: string;
        "name"?: string;
    }
    interface KgFooter {
    }
    interface KgIntro {
        "introtext"?: string;
    }
    interface KgLogo {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-root": AppRoot;
        "kg-background": KgBackground;
        "kg-card": KgCard;
        "kg-footer": KgFooter;
        "kg-intro": KgIntro;
        "kg-logo": KgLogo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "kg-background": LocalJSX.KgBackground & JSXBase.HTMLAttributes<HTMLKgBackgroundElement>;
            "kg-card": LocalJSX.KgCard & JSXBase.HTMLAttributes<HTMLKgCardElement>;
            "kg-footer": LocalJSX.KgFooter & JSXBase.HTMLAttributes<HTMLKgFooterElement>;
            "kg-intro": LocalJSX.KgIntro & JSXBase.HTMLAttributes<HTMLKgIntroElement>;
            "kg-logo": LocalJSX.KgLogo & JSXBase.HTMLAttributes<HTMLKgLogoElement>;
        }
    }
}
